#include "dimacs_w.h"
#include "graphe.h"

#include "stdio.h"

void writeDimacs(char* file, graphe g){
    FILE *f;
    f = fopen(file, "w");

    fprintf(f, "c This file was generated by DIMACS_conversion\nc\n");

    unsigned int nb_var;
    unsigned int nb_clause;

    nb_var = g.nb_point * g.nb_couleur;
    nb_clause = g.nb_point + g.nb_point * ((g.nb_couleur * (g.nb_couleur - 1)) / 2) + g.nb_segment * g.nb_couleur;

    #ifdef _DEBUG
        printf("il faut %d variables et %d clauses pour ce probleme\n", nb_var ,nb_clause);
    #endif // _DEBUG

    fprintf(f, "p cnf %d %d\nc\n", nb_var, nb_clause);


    /*un sommet doit avoir une couleur */
    fprintf(f, "c un sommet doit avoir une couleur\n");
    for (size_t i = 0; i < g.nb_point; i++) {
        for (size_t j = 1; j <= g.nb_couleur; j++) {
            fprintf(f, "%ld ", i*g.nb_couleur + j);
        }
        fprintf(f,"0\n");
    }
    fprintf(f, "c\n");

    /* un sommet ne peut prendre que une couleur */
    fprintf(f, "c un sommet ne peut prendre que une couleur\n");
    for (size_t i = 0; i < g.nb_point; i++) {
        fprintf(f,"c sommet %ld\n", i+1);
        int rang_point = i * g.nb_couleur;
        for (size_t j1 = 1; j1 < g.nb_couleur +1; j1++) {
            for (size_t j2 = j1; j2 < g.nb_couleur+1; j2++) {
                if (j1 != j2) {
                fprintf(f,"-%ld -%ld 0\n", rang_point + j1, rang_point + j2);
                }
            }
        }
    }
    fprintf(f, "c\n");

    /* deux sommets adjacents n'ont pas la meme couleur */
    fprintf(f, "c deux sommets adjacents n'ont pas la meme couleur\n");
    for (size_t i = 0; i < g.nb_segment; i++) {
        segment seg;
        seg = g.segments[i];
        sommet a = seg.a;
        sommet b = seg.b;
        for (size_t j = 1; j <= g.nb_couleur; j++) {
            fprintf(f, "-%ld -%ld 0\n", (a.id-1)*g.nb_couleur + j, (b.id-1)*g.nb_couleur + j);
        }
        fprintf(f ,"c\n");
    }

    fclose(f);
}